### ISSUE TITLE
Passenger side seat warmer

### ISSUE THREAD

**Issue by ChrisEdson** [dburkland/tesla_ios_shortcuts#1]
This is amazing! I have a humble request. Are you able to create a shortcut which turns on the HVAC and puts the passenger heater on full?

I basically do it for my wife every time I get in to the car!

**Comment by dburkland** [comment]
Thanks for the feedback! I can absolutely add that shortcut, will have sometime sunday to work on this. Stay tuned!

**Comment by dburkland** [comment]
@ChrisEdson download the new "Turn on HVAC Max Spouse" shortcut using the "Download Latest Tesla Shortcuts" shortcut on your device. Let me know if you have any issues!

**Comment by ChrisEdson** [comment]
Thanks so much for this! Incredibly kind of you. 

I wondered if you might consider open sourcing your AWS / Lambda code?

I’d love to run my own version (ideally so I can tweak some of the commands - temperature setting stuff etc, but also for token security).

Let me know if it’s something you’d think about 😊

**Comment by dburkland** [comment]
The plan is to open source it just need to find the time to update the documentation so I can post it to the public. Should have time in a few weeks, stay tuned!
