### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by tapiocateeh** [dburkland/tesla_ios_shortcuts#12]
Thank you for making these! 

I'm trying to follow your instructions and got to the point of creating the Tesla Token successfully. I can see the config.json file in my Shortcuts folder in my iCloud Drive. However, when i attempt to run any of the shortcuts dealing with the car (Honk Horn, Start Remote Drive, etc), I always get an "ERROR: Exiting as something went wrong..." It seems to be at the "Get contents of URL" part of the code. 

any thoughts? suggestions? please help!!

**Comment by dburkland** [comment]
Do you have the latest version of the "Create Tesla Token" shortcut? I would recommend doing the following:

* Delete the "Create Tesla Token" shortcut
* Delete the "config.json" file in the appropriate iCloud drive folder
* Download the latest "Create Tesla Token" shortcut using the Downloader shortcut
* Login to Tesla.com using your account credentials and make sure your account is not locked
* Re-run the "Create Tesla Token" shortcut and make sure it completes with a success (a fresh config.json should get created)

Let me know after all that if you are still running into issues and we can dig in a bit further.

Cheers,

Dan

**Comment by tapiocateeh** [comment]
I do have the latest version.  Thank you for your reply

I have followed your instructions, but without success. I have verified
that a fresh config.json was created. please let me know of any other ideas.

Much appreciated

**Comment by dburkland** [comment]
Are you on Twitter or social media @tapiocateeh? If you're on Twitter feel free to DM me there -> https://twitter.com/dburkland.

Thanks,

Dan

**Comment by mrd0n** [comment]
Hey Dan,

Nice work on the Tesla shortcuts and API!    I stayed up way too late last night, but managed to get the shortcuts working in my AWS account.

I’m on Reddit (u/dmunr0e) mostly, but also lurk on Instagram (mrd0n) and twitter (@mrd0n) - I reach out to you on twitter.

—Don

**Comment by dburkland** [comment]
@mrd0n I have some Terraform code to build everything out I just need to get around to publishing it. If you're interested I can send you a zip to play around with if you like.

Cheers!

Dan

**Comment by tapiocateeh** [comment]
I haven’t used twitter for years;  I’m not able to message you; maybe u can
message me (@tapiocateeh)
https://twitter.com/tapiocateeh

Thanks

**Comment by mrd0n** [comment]
@dburkland - I haven't used Terraform before but I'll add it to the list of things I'd like to learn.  Yes, when you have a sec, publish the code or shoot me the .zip.   

At first I thought of trying to modify the front/backend to work within a docker container so that I could run it beside my teslamate setup, but now that I have it working in my AWS account what's the point?   It looks super economic given that the components only run when triggered by the AWS API Gateway.    I learned a bunch getting this working last night - thank you!

**Comment by dburkland** [comment]
@mrd0n here you go -> https://www.dropbox.com/s/we5qnf5tdv0arq4/tesla_token_aws_lambda_function.zip?dl=0. And yea it's pretty much free to run Lambda functions so it makes it pretty compelling to just run code out there for things like this.

Cheers,

Dan

**Comment by dburkland** [comment]
This issue was resolved with the fix included in version 2.2. Thanks to @tapiocateeh for working with me on troubleshooting this one.

Cheers,

Dan
