### ISSUE TITLE
Leading 0 on MFA challenge response.

### ISSUE THREAD

**Issue by kdtjlamb** [dburkland/tesla_ios_shortcuts#13]
If an MFA response begins with a leading 0 (zero),  the input into the ‘create token’ shortcut seems to ignore or will not accept a zero for the first character.

**Comment by dburkland** [comment]
Thank you for submitting this! This was my first time using the "Number" input type in iOS shortcuts and I thought I had tested everything 🤦‍♂️. I will be releasing v2.1 which includes the fix for this issue so please let me know if you notice anything else wrong.

Cheers,

Dan

**Comment by kdtjlamb** [comment]
Dan - Works Great!.  Nice Job.   Really appreciate the work on this.   

Kevin
