### ISSUE TITLE
Can you share your Cloud based code

### ISSUE THREAD

**Issue by IMNotMax** [dburkland/tesla_ios_shortcuts#15]
Hi, nice work but can you share your cloud based code ?

**Comment by dburkland** [comment]
Hi @IMNotMax,

If you're interested in hosting yourself, I have published the code for both the token and command backends here:

* https://github.com/dburkland/tesla_token_aws_lambda_function
* https://github.com/dburkland/tesla_cmds_aws_lambda_functions

Cheers,

Dan

**Comment by IMNotMax** [comment]
thank you !
