### ISSUE TITLE
Download Latest Legacy Tesla Shortcuts updated??

### ISSUE THREAD

**Issue by j450h1** [dburkland/tesla_ios_shortcuts#16]
Is Download Latest Legacy Tesla Shortcuts actually downloading the latest version of
Create Tesla Token.shortcut?

I don't think so because it never asks for MFA code and am getting an error trying to generate a token (I followed troubleshooting steps as per README.md)?

**Comment by dburkland** [comment]
The legacy shortcuts are no longer being maintained so please make sure you are using the "Tesla iOS Shortcuts Downloader" shortcut available from here -> https://www.icloud.com/shortcuts/d3724ba6697c400dbb587f2df7049df5.

Cheers,

Dan
