### ISSUE TITLE
Tesla iOS Shortcuts Update Checker - Unavailable

### ISSUE THREAD

**Issue by j450h1** [dburkland/tesla_ios_shortcuts#17]
I've installed the shortcut to download other shortcuts. However, there is no option to download this Update Checker? How can I get this one?

**Comment by dburkland** [comment]
Make sure you have the latest download shortcut installed (delete the existing and download this one -> https://www.icloud.com/shortcuts/d3724ba6697c400dbb587f2df7049df5). Once installed re-run that shortcut and you should see the "Tesla iOS Shortcuts Update Checker" shortcut in the list if you scroll down a bit.

Let me know if this doesn't work for you.

Dan
