### ISSUE TITLE
Create Tesla Token is not working for me

### ISSUE THREAD

**Issue by HarryHung** [dburkland/tesla_ios_shortcuts#18]
It seems I cannot create a Tesla Token via the Shortcuts Script

1. Confirmed I can log into tesla.com
2. Confirmed my email address on tesla.com is all lowercases
3. Confirmed entering the right password and MFA code (Actually using a password manager, able to use the same manager to login tesla.com) 

Always get the 
`ERROR: Exiting as something went wrong...`

Try to troubleshoot a bit with the below code (email, password, and MFA code removed) on my PC, not sure if I have misunderstood anything
```
import requests

url = 'https://g8g6lwbtr0.execute-api.us-west-1.amazonaws.com/prod'
data = {
    'TESLA_EMAIL': '*****',
    'TESLA_PASSWORD': '*****',
    'TESLA_MFA_CODE': '*****'
}

resp = requests.post(url, json=data)
print("Status code: ", resp.status_code)
print(resp.json())
```
I always get one of the following responses:
```
Status code:  504
{'message': 'Endpoint request timed out'}
```
```
Status code:  200
{'statusCode': 400, 'ACCESS_TOKEN': 'ERROR_NO_TOKEN', 'REFRESH_TOKEN': 'ERROR_NO_REFRESH_TOKEN'}
```

My internet seems to be working fine. Tried with or without a VPN. 

Please let me know if you need more information. Thanks for your hard work!

**Comment by omarshahine** [comment]
I’m having the same issue / same error.

**Comment by SamiGloo** [comment]
Same issue on my end.

**Comment by dburkland** [comment]
I am working on troubleshooting an issue with the backend web service that the "Create Tesla Token" shortcut uses. Hope to have this fixed by tomorrow so stay tuned!

Dan

**Comment by dburkland** [comment]
It looks like Tesla is now blocking all auth requests coming from AWS so in the meantime I have updated the "Create Tesla Token" shortcut to rely on the freely available "Auth app for Tesla". To get started do the following:

* Delete the "Create Tesla Token" shortcut
* Look at the latest README.MD and follow the steps under "Prerequisites" & "Shortcut Setup".

Please let me know if you run into any further issues!

Dan

**Comment by HarryHung** [comment]
Hi Dan,

Thanks for recommending the app, I am able to create a token with it. 

I am curious that now we create the token on an app, why we still need to input the email and password in the "Create Tesla Token" shortcut? Having the token created by the app should be enough for other shortcuts to execute the command?

Thanks!

**Comment by dburkland** [comment]
Glad to hear!

The password is not needed unless you want to use the "Remote Start" shortcut. If you do not plan on using that shortcut simply enter in random text when prompted when running the updated "Create Tesla Token" shortcut.

Dan

**Comment by HarryHung** [comment]
Thanks for the prompt reply! Good to know that.
Again, thanks for all the efforts you have put into this project! Really appreciate it.
