### ISSUE TITLE
Error: executing command gives error message. File does not exist.  

### ISSUE THREAD

**Issue by dlb001** [dburkland/tesla_ios_shortcuts#19]
The file config.json can not be opened because it does not exists. Checked my icloud drive but there’s no config.json. 
Why is this file not created when running the “Create Tesla Token” script? Installed the script again.
How to get this correct config.json on my icloud drive?
Tesla model 3 software version: 2021.4.10

**Comment by dburkland** [comment]
I am working on troubleshooting an issue with the backend web service that the "Create Tesla Token" shortcut uses. Hope to have this fixed by tomorrow stay tuned!

Dan

**Comment by dlb001** [comment]
Hi Dan,

Thanks for your reply. Great that you are working on this issue.
I would like to use your scripts.

Greetings from the Netherlands,


Groet,

David

**Comment by dburkland** [comment]
It looks like Tesla is now blocking all auth requests coming from AWS so in the meantime I have updated the "Create Tesla Token" shortcut to rely on the freely available "Auth app for Tesla". To get started do the following:

* Delete the "Create Tesla Token" shortcut
* Look at the latest README.MD and follow the steps under "Prerequisites" & "Shortcut Setup".

Please let me know if you run into any further issues!

Dan

**Comment by dlb001** [comment]
Hi Dan,

Thanks for your reply. I’ll try to get this working based on your readme.

Groet,

David

**Comment by dlb001** [comment]
Hi Dan,

Want to let you know everything works fine now.
Thanks a lot.


Groet,

David

**Comment by dburkland** [comment]
Great news, thanks @dlb001!

Dan
