### ISSUE TITLE
Unlock Charge Port

### ISSUE THREAD

**Issue by ChrisEdson** [dburkland/tesla_ios_shortcuts#2]
Hello! Me again.

I have another (hopefully simple) request :)

Frequently - when walking up to the car after leaving it charging, have to go in to the Tesla app to unlock the charging door. Stopping charging, as a command, doesn't actually unlock the charge door - whereas 'Unlock charge port' both stops charging AND unlocks the cable, allowing you to remove it.

Can I put in a humble request for a new shortcut, which is 'Unlock charge port'?

Thank you so much!

**Comment by dburkland** [comment]
Hi Chris,

Is this still an issue for you?

Dan

**Comment by DanielWeeber** [comment]
Yeah, for me it is. I just want to unlock the charge cable. "Stop Charging" does not seem to unlock. So I have to open the tesla app manually and unlock the charge port insted of only using your shortcuts

**Comment by ChrisEdson** [comment]
Yep - still an issue :)

**Comment by gukj** [comment]
+1 on this. I made my own, but would be sweet to be able to only use shortcuts from this library.

**Comment by gukj** [comment]
Some background on the issue: I charge my Model 3 in a public garage that has chargers installed. For these I use a typical [Type 2-cabel from Mennekes](http://www.mennek.es/index.php?id=latest0&L=2&tx_ttnews[tt_news]=929&cHash=46a00bad7f0d569c00bea9537556bbeb), which doesn't have a release button for the charging port. Hence, whenever I walk up to my car, I have to either get in and unlock the charger from the screen in the car or I have to get my phone out, wait for the app to wake the car and then unlock the car. Having a shortcut for this that I could put on the home screen would be very nice.

As of November 3 (2020.48.5) the Model S and X don't have this issue anymore:

> You can now press the small black button to the left of the charge port inlet to unlatch the charge cable when your car is unlocked. This may be particularly useful when charging with charge cables that do not have a release button on the connector handle.

**Comment by gukj** [comment]
Just realized Tesla has combined the "Open charge port" and "Unlock charge port" commands in the API. So @DanielWeeber & @ChrisEdson — just download the "Open charge port" shortcut and everything should be good.

**Comment by dburkland** [comment]
That is correct @gukj, thanks for sharing that! I am considering this issue fixed however in the event it is not feel free to re-open or create a new one.

Cheers,

Dan
