### ISSUE TITLE
Siri Shortcut - Turn on Climate heat - Recommendations to rename?

### ISSUE THREAD

**Issue by j450h1** [dburkland/tesla_ios_shortcuts#20]
In the past, renaming/duplicating this shortcut to "Turn Heat On" would work to circumvent that annoying popup message: _It looks like you haven't set up any Homekit accessories: Open the Home app_

However, this trick no longer works. "Turn On Heat" also doesn't work. Not really an issue per se, just wondering if someone has a good idea to rename this so I can use it with Siri?

While we're at it? Any recommendation here?

* **Turn Off Climate**: Same similar message from Siri: _Please use your car's controls to adjust the climate control._

**Comment by j450h1** [comment]
I see you mentioned in the Readme as per below and used the same approach as me, but at least for me its no longer working:

_NOTE: Please keep in mind that the shortcut name must be unique from other shortcuts in your library. As an example, I tried to rename Turn on HVAC Normal to Turn on Heat, but that command is associated with HomeKit so it doesn't work. Turn Heat On however works perfectly fine._

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
