### ISSUE TITLE
Heat/cool car notifications returning °F instead of °C on EU spec car

### ISSUE THREAD

**Issue by himynamesned** [dburkland/tesla_ios_shortcuts#21]
As above. TeslaFi API if makes difference - config file shows:
`temperature_unit":""`

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
