### ISSUE TITLE
Auth app for Tesla

### ISSUE THREAD

**Issue by Kemmey** [dburkland/tesla_ios_shortcuts#25]
Hey Dan, 

I'm so glad you found the app and adopted it for your shortcuts! I specifically had you in mind when I added the token intent donations, and wanted to reach out and ask if you wanted to be featured in the "Friends of the app" section?

If you do want to be mentioned, could you get back to me with a square icon, name and url to feature? 

Cheers, 

Kim (dev of Auth app for Tesla)

**Comment by dburkland** [comment]
Hey @Kemmey,

Thanks for reaching out and for thinking of me & putting the work into the Auth App for Tesla, it is much appreciated! I would love a mention in the app. Below are the details you requested:

* Square Icon -> https://www.dropbox.com/s/vfcaov1jw9aouoz/18c714c61bfdebca44fe6989f0a2511d.png?dl=0
* Name: Tesla iOS Shortcuts
* URL to feature: https://github.com/dburkland/tesla_ios_shortcuts/blob/master/README.md

Thanks again,

Dan

**Comment by Kemmey** [comment]
Hey @dburkland 

Sorry about the radio silence - was on Easter holiday :-D 

I'll add your details now - I'll have it up in TestFlight here when done: 

https://testflight.apple.com/join/jTixIetK

Cheers,

Kim

**Comment by Kemmey** [comment]
@dburkland Update is now live in the store - app review works fast sometimes! :-D

**Comment by dburkland** [comment]
Awesome thanks @Kemmey!

Dan

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
