### ISSUE TITLE
Auth process changed? - conversion error

### ISSUE THREAD

**Issue by himynamesned** [dburkland/tesla_ios_shortcuts#26]
Getting errors on all my shortcuts now. Checked for latest versions. Think the teslamotors.com URL has changed. Can’t even get new token from TeslaFi. 

Any suggestions?

**Comment by himynamesned** [comment]
Any updates or suggestions?

**Comment by himynamesned** [comment]
Getting status code 400 It would seem and using TeslaFi key

**Comment by dburkland** [comment]
TeslaFi must have modified their token page so I will need to spend sometime seeing what they changed.

More to come...

Dan

**Comment by thepennster** [comment]
Hey Dan -

Just wanted to say thank you for all the work on this. It’s your personal time, and often and thankless, but your Shortcuts are awesome.

**Comment by MrSco** [comment]
Any updates for this? I’m having the same issue with Auth app for Tesla not exporting the token to the shortcut.

 I just got my new Model 3 and was so excited to trick it out with Siri powers!

**Comment by mrd0n** [comment]
I'm not sure if this helps, but I've been using the "Jayson" app to edit the config (ios_shortcuts/tesla/config.json) to update the token.   Basically Copy the refreshed token from the AuthAppForTelsa and paste into the field using the Jayson app.

**Comment by MrSco** [comment]
> I'm not sure if this helps, but I've been using the "Jayson" app to edit the config (ios_shortcuts/tesla/config.json) to update the token. Basically Copy the refreshed token from the AuthAppForTelsa and paste into the field using the Jayson app.

Unfortunately since auth app for Tesla doesn’t pass back the token (it generates fine and shows me it to copy) the config file never gets created. Can you share your blanked out config file as a template I can use? I don’t know what my vehicle id would be though...?

**Comment by mrd0n** [comment]
Sure - Here's what the config.json file looks like:
`
{
  "vehicle_id": "0123456789012345",
  "vehicle_name": "car_name",
  "temperature_unit": "Celsius",
  "tesla_email": "myemail@domain.com",
  "access_token": "qts-8e1xxxxxxx...",
  "tesla_password": "mypassword",
  "url": "https://kx6y5ro3w9.execute-api.us-west-1.amazonaws.com/prod"
}
`

To get the vehicle_id, you need to interact with the Tesla API.  I hacked one of Dan's shortcuts to do that with the Tesla Auth Token here:
https://www.icloud.com/shortcuts/c46318c289034b84816e9670b3644f57

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
