### ISSUE TITLE
Apple Watch Shortcuts Error

### ISSUE THREAD

**Issue by ghost** [dburkland/tesla_ios_shortcuts#28]
When trying to run shortcuts on my Apple Watch, it says unable tu get URL. 
Create token also fails because of no path to store the config file.

**Comment by tapiocateeh** [comment]
Bump? Same issue for me. "No URL specified" on Apple Watch

**Comment by WyldeCardz** [comment]
Same here. Would love to get this fixed. Voice commands would help a lot!

**Comment by macbethfan** [comment]
I'm also having this problem after updating to ios 15 and watchOS 8. I wasn't getting this error before then.

**Comment by NeskireDK** [comment]
Yup, Apple changed up things with iOS 15, [we are not alone in noticing this](https://www.reddit.com/r/shortcuts/comments/pu2kid/shortcuts_is_terrible_now_after_the_ios_15_update/)

**Comment by dburkland** [comment]
Hey all sorry for the delay in responding, work has been a bit crazy lately. I am aware of this issue (thanks Apple for breaking stuff again in watchOS 👎 ) and will hopefully have some time this weekend or next to come up with a solution. Appreciate your patience!

Dan

**Comment by NeskireDK** [comment]
Thanks for getting back to us all. You’re awesome. 
Appreciate you reposting the code for the AWS service. Never knew that. 

A last thanks, after now trying the paid competitors, I have to say, for my needs, these integrations are much preferred. Better, faster, simpler and compatible without drawbacks like extra battery drain. 

Cheers from Denmark.

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
