### ISSUE TITLE
Tesla Cloud API Access Gone

### ISSUE THREAD

**Issue by StachStach** [dburkland/tesla_ios_shortcuts#3]
Now that Tesla has taken away API access from the various clouds (Google, Azure, AWS), would it be possible to port your cloud API pieces to a users own Unix server or docker container? This way it will work again (Tesla isn't blocking all IP ranges) and the user would have complete control over the system and credentials?

**Comment by dburkland** [comment]
The code would require some tweaking to to run it on your own on-prem servers however I can add this to the list.

Dan

**Comment by dburkland** [comment]
If you're interested in hosting yourself, I have published the code for both the token and command backends here:

* https://github.com/dburkland/tesla_token_aws_lambda_function
* https://github.com/dburkland/tesla_cmds_aws_lambda_functions

Cheers,

Dan

**Comment by mrd0n** [comment]
I was able to get the frontend/backend working in my AWS account last night.   It was fun "reverse engineering" the setup required around Lambda, SNS, GitHub Actions, IAM roles/permissions, etc.   If someone want to try, I could take a stab at some documentation.

Dan - thank you for sharing this - well done!

**Comment by StachStach** [comment]
I am definitely interested in trying to get this running, in order to learn more about AWS. So is this able to run on an Always Free AWS Lamba tier?

**Comment by dburkland** [comment]
Correct you can host these for free.

Dan

**Comment by StachStach** [comment]
Just checking in to see if anyone has had a chance to make an install doc yet?

**Comment by dburkland** [comment]
@StachStach The closest to setup instructions for the Lambda pieces I have is some Terraform code which builds out all the AWS components. If you're interested DM me on Twitter @dburkland and I can shoot you the code.

Cheers,

Dan
