### ISSUE TITLE
iOS 15

### ISSUE THREAD

**Issue by tapiocateeh** [dburkland/tesla_ios_shortcuts#30]
Getting error of the following for all shortcuts:

The operation couldn't be
completed. (NSFileProvider-
ErrorDomain error -1005.)

Any ideas?

**Comment by NeskireDK** [comment]
I'm getting a little desperate here, waiting for Apple to update the shortcut app, to fix their bugs. But alas, I think its up to us users to fix it. Do anyone know how to work around these security to url related issues that Shortcuts now have? 
We cannot execute shortcuts from HomePod or Apple Watch anymore, even though they work perfect in practice on phone.

**Comment by dburkland** [comment]
Hey all sorry for the delay in responding, work has been a bit crazy lately. I am aware of this issue (thanks Apple for breaking stuff again in watchOS 👎 ) and will hopefully have some time this weekend or next to come up with a solution. Appreciate your patience!

Dan

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
