### ISSUE TITLE
Setup no longer working? iOS15

### ISSUE THREAD

**Issue by 1bigtree** [dburkland/tesla_ios_shortcuts#32]
I'm new to this marvelous offering, so perhaps I'm confused. But it seems like Tesla iOS Shortcuts Downloader isn't creating the file structure it's supposed to and thus when I run one of the shortcuts I get:

The file doesn't exist. 
The fiel "config.json" couldn't be opened because there is no such file.

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan

**Comment by 1bigtree** [comment]
Super appreciate the update!! Unfortunately, iOS 15 no longer allows untrusted shortcuts in the same way. The only option I see is to turn on "Private Sharing" in Settings -> Shortcuts, which allows receiving shortcuts from people in your contacts. I tried adding your name to my contacts and that didn't work. I tried adding dburkland and that didn't work. Any clue how to make this work?

**Comment by swotam** [comment]
Try turning Private Sharing OFF, that's how I have mine set and Dan's shortcuts work just fine.

**Comment by 1bigtree** [comment]
Unfortunately, I tried that first. Then I get the following message:

Shortcut Cannot Be Imported
This shortcut was received from
someone you may know, but it cannot be
opened because Private Sharing is
disabled in your Shortcuts preferences.

**Comment by swotam** [comment]
Maybe try enabling it again and reboot the phone. They changed the settings in iOS 15 so the option to Allow Untrusted isn't there anymore but presumably Private Sharing is the same setting with a different name...

**Comment by dburkland** [comment]
@swotam Thanks for sharing that. I am in the process of updating the README now with the workaround however feel free to open another issue if the problem persists @1bigtree.

Dan

**Comment by 1bigtree** [comment]
Works fabulously!!!! Tesla should hire you to implement this!!!!
