### ISSUE TITLE
Token lifespan 1 day not 1 month

### ISSUE THREAD

**Issue by daviegeepers** [dburkland/tesla_ios_shortcuts#33]
Has anyone else had the token lifespan be a day not a month? Everything works great but re-authenticating daily wouldn't work.

**Comment by dburkland** [comment]
I just released version 2.5 of Tesla iOS Shortcuts which now properly leverages Auth app for Tesla for all token-related functions (accessing / refreshing / etc). Please give them a try and if you still run into issues please open a new issue. Apologies for the delay in getting this new version pushed out!

Dan
