### ISSUE TITLE
Shortcuts not working on Apple Watch 

### ISSUE THREAD

**Issue by thepennster** [dburkland/tesla_ios_shortcuts#34]
Hi, I have the most recent shortcuts installed, however when trying to execute them on Watch OS 7.6.2 I get the following error: “No URL Specified. Make sure to pass a valid URL to the Get Contents of URL action”. The shortcuts works just fine on iOS.

**Comment by dburkland** [comment]
Any plans to upgrade to watchOS 8? It has been working fine for me on 8 since the last release.

Dan

**Comment by thepennster** [comment]
Is that a beta? I checked on my watch and I don’t have an update available.

**Comment by thepennster** [comment]
I’ll go ahead and close the issue, I’ll upgrade to 8. Thank you!!
