### ISSUE TITLE
Apple Watch grant access every run

### ISSUE THREAD

**Issue by ZEEN0j** [dburkland/tesla_ios_shortcuts#35]
Hi,

Running the latest version of the Tesla shortcuts 2.6 and watchOS 8.1 and I’m having to always allow access to auth token and files. They run fine on the phone after the initial grant access but on the watch I have to tap this every time. Is this how it’s supposed to work on the watch?

**Comment by ZEEN0j** [comment]
Also. Every time I run it on the watch I get the same question about access when running it on the phone. If I run it again after that on the phone it will work as expected.

**Comment by ZEEN0j** [comment]
This seems to me a shortcuts watchOS bug. The watch since watchOS 8 hasn’t been able to save shortcuts permissions

**Comment by dburkland** [comment]
I take it you tried deleting the shortcuts from the watch shortcuts app and trying again? If not then yeah it's a watchOS bug but not entirely surprising as Apple's QA as it pertains to Shortcuts has been severely lacking lately.

**Comment by ZEEN0j** [comment]
Yeah I’ve tried that. It works great on my phone. Thanks for this btw. 
Just hope Apple fixes it on the watch as that would be my ideal device for issuing commands
