### ISSUE TITLE
Create Tesla Token Missing?

### ISSUE THREAD

**Issue by JR-Horn** [dburkland/tesla_ios_shortcuts#36]
This looks awesome & is exactly what I have been looking for. I downloaded all of the shortcuts but when I try to download the Create Tesla Token one the circle in "Do:" just spins and there is nothing to download. Any idea's on why that is happening?

I tried to look through closed issues and didn't see this in there. Sorry if I missed it.

**Comment by dburkland** [comment]
I have not heard of anybody hitting this one yet, have you checked your iOS shortcut settings to make sure private sharing is disabled? If you could record a screen capture video of the issue that would be super helpful.

Thanks,

Dan

**Comment by JR-Horn** [comment]
I don't see an option to make private sharing disabled. I do have Allow Untrusted Shortcuts enabled. I've got all of the other shortcuts downloaded. I had this same issue with the downloader link but was able to find one that worked in the comments of closed issues. Below is a link to a screen capture of what happens. 

https://share.icloud.com/photos/0Qe4HxLA9Zw3FJSChTZp5F0hw

**Comment by JR-Horn** [comment]
I'm not sure if anything was changed or if the latest update on my phone did something but I was finally able to download a working version of the Create Tesla Token. All is working now!
