### ISSUE TITLE
shortcuts in China

### ISSUE THREAD

**Issue by ppttvs** [dburkland/tesla_ios_shortcuts#37]
Hi! I’m a Chinese tesla user and I’m trying to use these shortcuts. But I can only run Get Token…… config.json is generated successfully so I’m wondering if there is any problem with this AWS? Would you please test this function?

Here is the reply from shortcut when I was trying to set charge limit:
{"PARAMETER_2":"","statusCode":400,"BASE_URL":"https:\/\/owner-api.teslamotors.com\/api\/1\/vehicles\/","INITIAL_VEHICLE_STATE":null,"PARAMETER_1":"50","VEHICLE_ID":"xxxxxxxxxxxxxxxxx","INPUT_CMD":"set_charge_limit"}

xxxxxxxxxx is my vehicle id and it’s correct.

**Comment by dburkland** [comment]
See my answer here: https://github.com/dburkland/tesla_ios_shortcuts/issues/38#issuecomment-1081309623

Dan
