### ISSUE TITLE
issue in China

### ISSUE THREAD

**Issue by paysenyu** [dburkland/tesla_ios_shortcuts#38]
"Create Tesla Token"  - - I have generated a fresh authentication token for your Tesla and saved the output to /Shortcuts/ios_shortcuts/tesla/config.json inside your iCloud Drive.   

and then run any shortcut "ERROR: Exiting as something went wrong...""

**Comment by dburkland** [comment]
Tesla no longer accepts API requests from outside mainland China for Chinese-based Tesla vehicles. One workaround would be for me to host my backend serverless functions in a Chinese region of AWS (which I'm looking into).

More to come on this...

Dan

**Comment by paysenyu** [comment]
thanks
