### ISSUE TITLE
No URL Specified

### ISSUE THREAD

**Issue by g0nad** [dburkland/tesla_ios_shortcuts#4]
When running a number of shortcuts (turn on hvac normal for example) its returning this error:

Make sure to pass a valid URL to the Get Contents of URL action.

I've tried to redownload the shortcut with the same results.

**Comment by dburkland** [comment]
Hi @g0nad,

The issue you were running into was more than likely caused by the Tesla API outage that occurred for a good chunk of yesterday. Please let me know if everything works now and if so I will close this issue.

Thanks,

Dan

**Comment by g0nad** [comment]
Thanks for your quick reply Dan.  That is exactly what it was.  This issue can be closed
