### ISSUE TITLE
Impossible to generate a token

### ISSUE THREAD

**Issue by Kermarc44** [dburkland/tesla_ios_shortcuts#40]
Hello,

when I try to generate a token with the shortcut, I have this message :

Numerical argument out
of domain
The index you specified was outside
the possible range (you asked for item
2, but the list only has 1).

**Comment by simoncleal** [comment]
Hi,

I have the same error message on an iphone 13 pro max, iOS 15.5 is there a solution for this? Please? Does this error relate to the Refresh and Access Tokens generated within  the Auth for Tesla App?

**Comment by neotaruntius** [comment]
Facing the same issue. Oof!

**Comment by neotaruntius** [comment]
Ah, figured it out. The “Create Tesla Token” shortcut has been programmed to pick up a list of Teslas, that is, if you own that many. It does not handle the use-case for “poor” people with only one Tesla. So open the shortcut, go to the section where it says “Get Item at Index 2 from Dictionary Value” and remove any references to vehicle 2. That’ll get you going! :)

**Comment by simoncleal** [comment]
> Ah, figured it out. The “Create Tesla Token” shortcut has been programmed to pick up a list of Teslas, that is, if you own that many. It does not handle the use-case for “poor” people with only one Tesla. So open the shortcut, go to the section where it says “Get Item at Index 2 from Dictionary Value” and remove any references to vehicle 2. That’ll get you going! :)

Thank you. That sorted it for me. Although I haven't tried the other shortcuts yet. One issue I forsee though is that if you do an update it would probably overwrite the changes. Perhaps the nice man who created this shortcut set might add an option to ask for how many cars a person has!!?

**Comment by dburkland** [comment]
Hmm this is interesting as I did some testing with another Tesla account that has access to only 1 car and it seemed to work fine. I'll have to do some additional testing with this with a separate tesla account here soon.

Dan

**Comment by llamafilm** [comment]
I found the same problem on macOS 12.5 and iOS 15.6.1.  I wonder if older Shortcuts versions tolerated this kind of error silently?

The API response has only a single dict in the response array.  Perhaps the API syntax changed recently?  It looks like you should be able to read the `count` value first.

```json
{
  "count": 1,
  "response": [
    {
      "id": xxxx,
      "state": "asleep",
      "backseat_token": null,
      "in_service": false,
      "vin": "xxxx",
      "access_type": "OWNER",
      "api_version": 44,
      "color": null,
      "vehicle_id": xxxx,
      "display_name": "xxxx",
      "backseat_token_updated_at": null,
      "tokens": ["xxxx", "xxxx"],
      "id_s": "xxxx",
      "calendar_enabled": true,
      "option_codes": "AD15,AF00,APFB,APH4,AU3P,BC3B,BT42,CDM0,CH16,COUS,DRLH,DV4W,FC02,FG31,FM3B,GLFR,HL32,HM30,ID3A,IL31,LT03,MDL3,MR31,PPSW,PC30,RENA,RF3G,RS3H,S3PW,SA3P,SC04,STCP,SU3C,T3MA,TM00,TW00,UT3P,W40B,WR00,ZINV,MI02,PL30,SLR0,ST33,BG31,I36M,USSB,AUF1,RSF1,ILF1,FGF1,CPF1,P3WS,HP31,PT01,RL31,FD00,RD01,SWF1,RA00"
    }
  ]
}
```

**Comment by stealth006** [comment]
Owner of a single Tesla here, I can report the same issue. To fix I changed the index from 1 and 2 to first and last. 

This has the effect of showing 2 listings for the same vehicle but at least no error and may be an easy fix for now.

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
