### ISSUE TITLE
Tesla PowerWall support?

### ISSUE THREAD

**Issue by Edison517** [dburkland/tesla_ios_shortcuts#42]
Would it be possible to add support for controlling a Tesla PowerWall? There is an API that's documented here: [https://github.com/vloschiavo/powerwall2](https://github.com/vloschiavo/powerwall2)

This would allow owners to control the settings on a schedule, something that the Tesla app doesn't allow us to do.

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
