### ISSUE TITLE
Shortcuts Stopped Working

### ISSUE THREAD

**Issue by Jbb08** [dburkland/tesla_ios_shortcuts#43]
All of a sudden when my shortcuts are run, they complete perfectly with no errors however the Tesla does not do what is requested. Open Trunk or Turn Sentry Mode off or on is what I use mostly.
I’ve checked I can access my Tesla account and it’s not blocked or locked.
The car was updated to 2022.20.5 and I’m not sure if that’s the reason?
I use these shortcuts in automations for Sentry mode so I love them.
Is there anything I can do to try fix this?

**Comment by makeithapn** [comment]
I also have this problem. Open charge port works but open trunk and frunk do not

**Comment by dudutwizer** [comment]
It seems that only the sentry api is broken

**Comment by Jbb08** [comment]
> It seems that only the sentry api is broken

Frunk Open, Trunk Open or Close and All Sentry options do not work.
Honk Horn works..
So I think it's more that the API calls might have been updated?
I will delete all shortcuts and all automations and start again and see if a new token will help?

**Comment by dburkland** [comment]
Sorry all been a bit busy and just getting to this now. I'm seeing the same thing on my end and will do some digging and post some updates later this weekend.

Dan

**Comment by dburkland** [comment]
Update: The issue is caused by a recent API change Tesla made (see here: https://github.com/timdorr/tesla-api/issues/594). I have to update a bunch of code on my backend Lambda function however thankfully this is fairly easy and is something I should cranked out by tomorrow AM. I did some testing and confirmed the fix works with the start & stop sentry commands (try for yourself). 

Dan

**Comment by dburkland** [comment]
This issue has been resolved for all affected commands, please re-open this issue if you continue to run into issues.

Cheers,

Dan

**Comment by Jbb08** [comment]
Thanks @dburkland all working apart from Close Trunk it doesn't have 25 actions like all others (only 1) therefore does not work...
