### ISSUE TITLE
Error when adding shortcut

### ISSUE THREAD

**Issue by sj10lon** [dburkland/tesla_ios_shortcuts#45]
When trying to add any of the shortcuts to my Shortcuts app, I get the following message:

`Snarveien kan ikke åpnes fordi avsenderen ikke står oppført i kontaktene dine.`

Translated to English, that is:
`The shortcut cannot be opened because the sender is not listed in your contacts.`

What can I do here?

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
