### ISSUE TITLE
Unlock charge port shortcut?

### ISSUE THREAD

**Issue by tsvendson** [dburkland/tesla_ios_shortcuts#46]
Hi,

is it possible to create this shortcut? 

My home charger’ handle button is broken. So I need to open my app to unlock the charge port everyday.  

Thank you!

**Comment by tsvendson** [comment]
Sorry, just realized the stop charging short cut does this and solves my problem.

thank you for putting in the work to create these!

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
