### ISSUE TITLE
New Open Door Action for Model 3 & Y

### ISSUE THREAD

**Issue by fergymcferguson** [dburkland/tesla_ios_shortcuts#47]
Would it be possible to create a shortcut for the new “open door” action that was added to the Tesla app?  I know this just came out and you likely haven’t had a chance to do this yet, but it would be a nice addition!

Thanks in advance!

**Comment by Jbb08** [comment]
I agree @dburkland any chance we can have this shortcut updated to include open door?

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
