### ISSUE TITLE
Download attempts result in Shortcut cannot be opened

### ISSUE THREAD

**Issue by sppatel** [dburkland/tesla_ios_shortcuts#5]
On ios 14 attempting to download some of the shortcuts though the "Download shortcuts" app OR manually directly from the URL results in an error "shortcut could not be opened".  Some shortcuts from this inventory can be downloaded, others cannot such as "Unlock Doors".

**Comment by dburkland** [comment]
Thanks for the heads up, I am in the process of pushing updates out so check back tomorrow as any issues should be resolved with this push.

Thanks,

Dan

**Comment by dburkland** [comment]
I pushed v1.8 of the shortcuts today so this error should now be fixed. Feel free to re-open if this is still an issue for you.

Cheers,

Dan

**Comment by sppatel** [comment]
awesome will check it out ty
