### ISSUE TITLE
Get vehicle_state

### ISSUE THREAD

**Issue by lytesout2376** [dburkland/tesla_ios_shortcuts#50]
Is there any way to get vehicle_state? For example, my garage hits the front trunk if it is open when I open the garage. So I’d like to check if the front trunk is open before asking HomeKit to open the garage.

**Comment by dburkland** [comment]
The upstream AWS functions will return basic vehicle state information like whether or not the car is awake / asleep but that is pretty much it. Do you know if the car stays awake with the frunk open?

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
