### ISSUE TITLE
Can you add Steering Wheel Heater OFF option?

### ISSUE THREAD

**Issue by k8k901007** [dburkland/tesla_ios_shortcuts#51]
Turn On Climate Cool
Wakes the vehicle (if needed), turns on the Climate Control system, and sets the temperature to 66 degrees Fahrenheit (19 degrees Celsius).

2022.44.25.3
If I use this option("Turn On Climate Cool") the steering wheel heat gets automatically on. Even the seets too.
No needed in summer.

**Comment by dburkland** [comment]
These shortcuts have been deprecated by the official ones from Tesla.
