### ISSUE TITLE
Numerical Argument Out Of Domain

### ISSUE THREAD

**Issue by DarthKeidran** [dburkland/tesla_ios_shortcuts#53]
No matter what I do (including uninstalling and reinstalling) I receive these error messages when I try to execute the “Create Tesla Token” shortcut.

![IMG_8221](https://user-images.githubusercontent.com/131555830/233805214-d9815b86-7981-414a-913b-a4620b3fd23e.png)
![IMG_8222](https://user-images.githubusercontent.com/131555830/233805220-82cf78fc-d0e4-4e45-95e1-47756ef15808.png)

**Comment by sudip839981** [comment]
I changed the index to 1 and it worked. There are two places you need to change the index.
