### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by jackcox10** [dburkland/tesla_ios_shortcuts#6]
Ever since I upgraded to an iPhone 12 pro (previously had iPhone X) I’ve been getting the conversion error as shown in your explanation but following those steps doesn’t seem to fix it for me :(

**Comment by dburkland** [comment]
Do you happen to use any other 3rd party Tesla apps? If so you are more than likely running into this issue which is a result of Tesla's Multi-Factor Authentication system -> https://github.com/adriankumpf/teslamate/discussions/981#discussioncomment-165807. There are a few workarounds if this is indeed what you are hitting.

Dan

**Comment by dburkland** [comment]
@jackcox10 I updated the README to include additional details about how to handle this particular issue underneath the "Create Tesla Token" bullet. Feel free to re-open or message me on Twitter if you continue to experience issues.

Cheers,

Dan
