### ISSUE TITLE
Hidden Connection to AMAZON? 

### ISSUE THREAD

**Issue by Marcoqwerty78** [dburkland/tesla_ios_shortcuts#8]
Sorry but...can you explain me this?

![87D7E80E-F1B0-4229-80FD-2C6E5BC8DEB7](https://user-images.githubusercontent.com/39671834/102619482-d4dc9080-413c-11eb-95ff-73398acbc243.png)

**Comment by dburkland** [comment]
Hi Marco,

The use of AWS-based functions is not hidden, in fact it is mentioned several times in the README:

- "As a result, I have developed a new set of iOS shortcuts along with a cloud-based API service. These shortcuts are much simpler as the logic for dealing with things like vehicle state are now handled by the Cloud API service. Shortcuts now take only seconds to run regardless of what state the vehicle is in or how slow your mobile device's network connection is (as long as it is available). The Cloud API service is something I created myself in Python and host as a set of Amazon Web Services (AWS) Lambda Functions."
- "The authentication token that is created by the "Create Tesla Token" shortcut is stored in your personal iCloud Drive. The authentication token is only visible to apps or services that have access to your iCloud Drive meaning folks cannot publicly access this data by default.
When a shortcut is executed, the authentication token is sent to the Cloud API service using TLS where it is then used to communicate with Tesla. The authentication token is never logged or recorded in any way, shape or form.
NOTE: I do NOT log or record any usage data, nor do I log or record any of the created Tesla API tokens."

The first time you run each shortcut you will get asked for permission to talk to the AWS-based Lambda function (this is imposed by the Shortcuts app and something I cannot make go away).

Cheers

Dan
